apiVersion: v1
kind: Service
metadata:
  labels:
    app: jpetstoreweb
  name: jpetstore
spec:
  type: LoadBalancer  # use LoadBalancer as type here
  # loadBalancerIP: {{ .Values.IP }}
  ports:
    - port: 9080
  selector:
    app: jpetstoreweb

